apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-edmn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-edmn@sha256:ee84aa17c32437252819d3f7c44c516666ead93dd8a73c91c517d690a63f7694
        name: my-nodejs
        resources: {}
status: {}
